env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  allowImportEverywhere: true
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2015
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0

